import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Variable, Weight } from "lucide-react";

const jetbrainsMono = JetBrains_Mono(
  {
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: "--font-jetbrains-mono",
   },);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.className}>{children}</body>
    </html>
  );
}
